routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('station', 'StationController');

Route::get('/metar', 'MetarController@getData')->name('metar');

app/Station.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Station extends Model
{
    protected $table = 'stations';
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'icao', 'latitude', 'longitude',
    ];
    
    public function current_weather()
    {
        return $this->hasMany('App\CurrentWeather');
    }
}

app/Http/Controllers/StationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Station;
use Illuminate\Support\Facades\Validator;

class StationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('station.index')->with('stations', Station::all());
    }
    
    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => ['required', 'string', 'max:50'],
            'icao' => ['required', 'string', 'max:4'],
            'latitude' => ['required', 'double'],
            'longitude' => ['required', 'double'],
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {        
        return view('station.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validator([
            $request->name, 
            $request->icao, 
            $request->latitude, 
            $request->longitude
        ]);
        
        Station::create([
            'name' => $request->name,
            'icao' => $request->icao,
            'latitude' => $request->latitude,
            'longitude' => $request->longitude,
        ]);
        
        return redirect(route('station.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/station/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @auth
    <div class="row justify-content-center mt-5">
        <h2>Adding Station Data</h2>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-8">
            @if($errors->any())
            <div class="alert alert-danger">
                <ul class="list list-group">
                    @foreach($errors->all() as $error)
                    <li class="list-group-item text-danger">
                        {{ $error }}
                    </li>
                    @endforeach
                </ul>
            </div>
            @endif
            <form action="{{ route('station.store') }}" method="post">
                @csrf
                <div class="form-group">
                    <label for="exampleInputEmail1">Station name</label>
                    <input name="name" type="text" class="form-control" id="exampleStation" aria-describedby="emailHelp">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">ICAO Index Number</label>
                    <input name="icao" type="text" class="form-control" id="exampleIcao">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Latitude</label>
                    <input name="latitude" type="number" step="0.1" class="form-control" id="exampleLat">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Longitude</label>
                    <input name="longitude" type="number" step="0.1" class="form-control" id="exampleLong">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
    @endauth
</div>
@endsection

resources/views/station/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

            @if (session('status'))
            <div class="alert alert-success" role="alert">
                {{ session('status') }}
            </div>
            @endif
        </div>
    </div>

    @auth
    <div class="row justify-content-center mt-5">
        <h2>All Stations</h2>
    </div>
    <div class="row justify-content-center mb-4"><a href="{{ route('station.create') }}" class="btn btn-success pull-right" >New Station</a></div>
    <div class="row justify-content-center">
        <div class="col-md-8">
            @if($stations)
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Title</th>
                        <th scope="col">Icao</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($stations as $station)
                    <tr>
                        <th scope="row">{{ $station->id }}</th>
                        <td>{{ $station->name }}</td>
                        <td>{{ $station->icao }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            @else
            <p>Empty data</p>
            @endif
        </div>
    </div>
    @endauth
</div>
@endsection